name: Build the web site
on:
  push:
    branches: ["develop"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Do the build
        run: |
          chmod +x ./scripts/release.sh
          bash ./scripts/release.sh
          rm -rf ./scripts
          git add .
          git commit -m "${{github.event.head_commit.message}}"
          git push origin release --force

          
