name: Build the web site
on:
  push:
    branches: ["develop"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Node JS
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Do the build
        run: |
          chmod +x ./scripts/release.sh
          ./scripts/release.sh
          rm -rf ./scripts
          git add .
          git commit -m "${{github.event.head_commit.message}}"
      - name: Push the changes to the release branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: release

          
